// Code generated by "stringer -type=Pill"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified-0]
	_ = x[Placebo-1]
	_ = x[Aspirin-2]
	_ = x[Ibuprofen-3]
	_ = x[Paracetamol-4]
}

const _Pill_name = "UnspecifiedPlaceboAspirinIbuprofenParacetamol"

var _Pill_index = [...]uint8{0, 11, 18, 25, 34, 45}

func (i Pill) String() string {
	if i < 0 || i >= Pill(len(_Pill_index)-1) {
		return "Pill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Pill_name[_Pill_index[i]:_Pill_index[i+1]]
}
